trigger: none
pool: Agentvm
stages:
- stage: BuildStage
  displayName: BuildStage
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
  
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-connecton'
        repository: 'MicroTodoUI'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
